"""
Summarize visualizer output PNG files into a CSV matrix.

This utility scans the current or specified directory for files matching
trend_{stock_id}{name_suffix}_{end_date}.png and produces a CSV file named
summary.csv by default.

The output includes:
- stock_id
- stock_name
- 出現次數
- one column for each unique end date found in the PNG filenames

A mark of "◯" indicates the stock appeared for a given date; blank means it did not.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


DATE_FORMAT = "%Y-%m-%d"


def parse_visualizer_filename(path: Path) -> tuple[str, str, str] | None:
    """Parse filenames generated by institutional_net_buy_visualizer.py."""
    stem = path.stem
    if not stem.startswith("trend_"):
        return None

    body = stem[len("trend_") :]
    if "_" not in body:
        return None

    name_part, date_part = body.rsplit("_", 1)
    parsed_date = pd.to_datetime(date_part, format=DATE_FORMAT, errors="coerce")
    if pd.isna(parsed_date):
        return None

    if "_" in name_part:
        stock_id, stock_name = name_part.split("_", 1)
    else:
        stock_id = name_part
        stock_name = ""

    return stock_id, stock_name, parsed_date.strftime(DATE_FORMAT)


def build_summary_table(directory: Path) -> pd.DataFrame:
    """Build a dataframe with stock occurrence counts and date markers."""
    png_files = sorted(directory.glob("trend_*.png"))
    records: dict[tuple[str, str], set[str]] = {}
    all_dates: set[str] = set()

    for png_file in png_files:
        parsed = parse_visualizer_filename(png_file)
        if parsed is None:
            continue

        stock_id, stock_name, date_str = parsed
        key = (stock_id, stock_name)
        records.setdefault(key, set()).add(date_str)
        all_dates.add(date_str)

    if not records:
        return pd.DataFrame()

    sorted_dates = sorted(all_dates)
    rows: list[dict[str, object]] = []
    for (stock_id, stock_name), appeared_dates in sorted(records.items(), key=lambda item: (item[0][0], item[0][1])):
        row: dict[str, object] = {
            "stock_id": stock_id,
            "stock_name": stock_name,
            "出現次數": len(appeared_dates),
        }
        for date in sorted_dates:
            row[date] = "◯" if date in appeared_dates else ""
        rows.append(row)

    columns = ["stock_id", "stock_name", "出現次數"] + sorted_dates
    return pd.DataFrame(rows, columns=columns)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate summary.csv from trend_*.png visualizer output files."
    )
    parser.add_argument(
        "--directory",
        type=str,
        default=".",
        help="Directory containing trend_*.png files.",
    )
    parser.add_argument(
        "--output-csv",
        type=str,
        default="summary.csv",
        help="Output CSV filename.",
    )
    args = parser.parse_args()

    directory = Path(args.directory)
    if not directory.exists() or not directory.is_dir():
        raise SystemExit(f"Directory not found: {directory}")

    summary_df = build_summary_table(directory)
    if summary_df.empty:
        print("No matching trend_*.png files were found in the target directory.")
        return

    output_path = directory / args.output_csv if not Path(args.output_csv).is_absolute() else Path(args.output_csv)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    summary_df.to_csv(output_path, index=False, encoding="utf-8-sig")
    print(f"Summary saved to: {output_path}")


if __name__ == "__main__":
    main()
